name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tox:
    strategy:
      matrix:
        include:
          - env: py38
            python-version: 3.8
          - env: py39
            python-version: 3.9
          - env: py310
            python-version: '3.10'
          - env: py311
            python-version: 3.11
          - env: py312
            python-version: 3.12
          - env: py313
            python-version: 3.13
          - env: lint
            python-version: 3.13
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox for environment ${{ matrix.env }}
        run: tox -e ${{ matrix.env }}
